# -*- coding: utf-8 -*-
"""BikeStore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SVsFqEZa5Uwau1iTPZOSb1LPb5X_A_wb

# **Data Exploration**

> improt csv file

> get first 5 rows and last 5 rows

> exploring columns data types

> null values

> unique values

> sorting
"""

import numpy as np
import pandas as pd
df2 = pd.read_csv('BikeStores.csv')
df2

df2.head()

df2.tail()

df2.isna().sum()

df2.city.nunique()

df2.state.unique()

df2.info()

df2.duplicated().sum()

df2.sort_values(by ='order_id', ascending = True)

"""# Selecting and Filtering"""

##max rev
df2['revenue'].max()

##state have the max rev
df2[df2['revenue']==df2['revenue'].max()]['state'].unique()

##category have the min rev
df2[df2['revenue']==df2['revenue'].max()]['category_name'].unique()

## total revenue
df2['revenue'].sum()

## total orders
df2['order_id'].count()

## total quantity
df2['total_units'].sum()

##which category has the min revenue
df2[df2['revenue']==df2['revenue'].min()]['category_name'].unique()

##max revenue by category name
df2.groupby('category_name')['revenue'].max()

##top state and category by revenue
df2.groupby(['category_name','state'])['revenue'].max()

df2.groupby('category_name') .agg(
    mean_rev=('revenue', np.mean),
    sum_rev=('revenue', np.sum))